#message:28:(PartnerDesc_Goombario_World) {
	Press [C-DOWN] to have him tell you[BR]
	about everything nearby.[End]
}

#message:28:(PartnerDesc_Goombario_Battle) {
	He can describe enemies.[BR]
	His specialty is headbonking.[End]
}

#message:28:(PartnerDesc_Goombario_Battle_Headbonk) {
	Headbonk an enemy.[End]
}

#message:28:(PartnerDesc_Goombario_Battle_Tattle) {
	See enemy description and make[BR]
	HP visible.[End]
}

#message:28:(PartnerDesc_Goombario_Battle_Charge) {
	Charge attack power. It goes up[BR]
	by 2 then returns to normal.[End]
}

#message:28:(PartnerDesc_Goombario_Battle_Multibonk) {
	Headbonk continuously until[BR]
	you miss an action command.[End]
}

#message:28:(PartnerDesc_Goombario_Pause) {
	Goombario is a clever young[BR]
	adventurer who admires Mario.[BR]
	Press [C-DOWN] to have him tell you[BR]
	about everything nearby.[BR]
	His specialty is headbonking.[BR]
	[End]
}

#message:28:(PartnerDesc_Goombario_Pause_Headbonk1) {
	Headbonk an enemy.[End]
}

#message:28:(PartnerDesc_Goombario_Pause_Headbonk2) {
	Headbonk an enemy.[End]
}

#message:28:(PartnerDesc_Goombario_Pause_Headbonk3) {
	Headbonk an enemy.[End]
}

#message:28:(PartnerDesc_Goombario_Pause_Tattle) {
	See enemies' descriptions and[BR]
	see their HP during battle.[End]
}

#message:28:(PartnerDesc_Goombario_Pause_Charge) {
	Charge to raise attack power[BR]
	by 2.[BR]
	You can charge unlimited times,[BR]
	but power fades after attack.[BR]
	[End]
}

#message:28:(PartnerDesc_Goombario_Pause_Multibonk) {
	Headbonk continuously until[BR]
	you miss the action command.[End]
}

#message:28:(PartnerDesc_Kooper_World) {
	Press [C-DOWN] to reach an item[BR]
	a short distance away.[End]
}

#message:28:(PartnerDesc_Kooper_Battle) {
	His specialty is attacking[BR]
	enemies on the ground.[End]
}

#message:28:(PartnerDesc_Kooper_Battle_ShellToss) {
	Throw a shell at an enemy.[End]
}

#message:28:(PartnerDesc_Kooper_Battle_PowerShell) {
	Throw a shell at all enemies[BR]
	on the ground.[End]
}

#message:28:(PartnerDesc_Kooper_Battle_DizzyShell) {
	Daze and paralyze all enemies[BR]
	on the ground.[End]
}

#message:28:(PartnerDesc_Kooper_Battle_FireShell) {
	Attack all enemies on the ground[BR]
	with a flaming shell.[End]
}

#message:28:(PartnerDesc_Kooper_Pause) {
	This adventure-loving Koopa[BR]
	wants to be an archaeologist.[BR]
	He admires Kolorado, a world-[BR]
	renowned expert in archaeology.[BR]
	Press [C-DOWN] to toss a shell and[BR]
	reach items at a short distance.[BR]
	His specialty is attacking[BR]
	enemies on the ground.[End]
}

#message:28:(PartnerDesc_Kooper_Pause_ShellToss1) {
	Throw a shell at an enemy.[End]
}

#message:28:(PartnerDesc_Kooper_Pause_ShellToss2) {
	Throw a shell at an enemy.[End]
}

#message:28:(PartnerDesc_Kooper_Pause_ShellToss3) {
	Throw a shell at an enemy.[End]
}

#message:28:(PartnerDesc_Kooper_Pause_PowerShell) {
	Throw a shell at all enemies[BR]
	on the ground.[End]
}

#message:28:(PartnerDesc_Kooper_Pause_DizzyShell) {
	Daze and paralyze all enemies[BR]
	on the ground.[End]
}

#message:28:(PartnerDesc_Kooper_Pause_FireShell) {
	Attack all enemies on the ground[BR]
	with a flaming shell.[End]
}

#message:28:(PartnerDesc_Bombette_World) {
	Press [C-DOWN]. She'll explode and[BR]
	destroy cracked walls or rocks.[End]
}

#message:28:(PartnerDesc_Bombette_Battle) {
	Her specialty is exploding.[End]
}

#message:28:(PartnerDesc_Bombette_Battle_BodySlam) {
	Body Slam an enemy.[End]
}

#message:28:(PartnerDesc_Bombette_Battle_Bomb) {
	Explode and destroy an enemy[BR]
	on the ground.[End]
}

#message:28:(PartnerDesc_Bombette_Battle_PowerBomb) {
	Explode and destroy all enemies[BR]
	on the ground.[End]
}

#message:28:(PartnerDesc_Bombette_Battle_MegaBomb) {
	Explode and destroy all enemies.[End]
}

#message:28:(PartnerDesc_Bombette_Pause) {
	Hot-headed Bombette was once[BR]
	jailed in Koopa Bros. Fortress.[BR]
	Her specialty is blasting open[BR]
	cracked walls and rocks.[BR]
	Press [C-DOWN]. She'll walk off and[BR]
	explode, creating openings.[BR]
	Press [C-DOWN] while she's walking to[BR]
	make her blow up on the spot.[BR]
	[BR]
	[End]
}

#message:28:(PartnerDesc_Bombette_Pause_BodySlam1) {
	Body Slam an enemy.[End]
}

#message:28:(PartnerDesc_Bombette_Pause_BodySlam2) {
	Body Slam an enemy.[End]
}

#message:28:(PartnerDesc_Bombette_Pause_BodySlam3) {
	Body Slam an enemy.[End]
}

#message:28:(PartnerDesc_Bombette_Pause_Bomb) {
	Explode and destroy an enemy[BR]
	on the ground.[End]
}

#message:28:(PartnerDesc_Bombette_Pause_PowerBomb) {
	Explode and destroy all enemies[BR]
	on the ground.[End]
}

#message:28:(PartnerDesc_Bombette_Pause_MegaBomb) {
	Explode and destroy all enemies.[End]
}

#message:28:(PartnerDesc_Parakarry_World) {
	He delivers mail and can fly Mario[BR]
	over short gaps (press [C-DOWN]).[End]
}

#message:28:(PartnerDesc_Parakarry_Battle) {
	His specialty is attacking[BR]
	enemies in the air.[End]
}

#message:28:(PartnerDesc_Parakarry_Battle_SkyDive) {
	Kick an enemy.[End]
}

#message:28:(PartnerDesc_Parakarry_Battle_ShellShot) {
	Attack an enemy in the air[BR]
	by bumping into it.[End]
}

#message:28:(PartnerDesc_Parakarry_Battle_AirLift) {
	If it works, will carry an enemy[BR]
	away from the battle.[End]
}

#message:28:(PartnerDesc_Parakarry_Battle_AirRaid) {
	Fly around like crazy, attacking[BR]
	all enemies.[End]
}

#message:28:(PartnerDesc_Parakarry_Pause) {
	He's a mail-carrying Paratroopa[BR]
	who's looking for lost mail.[BR]
	Press [C-DOWN] to have him carry[BR]
	Mario for short distances.[BR]
	While he's carrying Mario, press[BR]
	[C-DOWN] again to put him down.[BR]
	He can deliver letters to[BR]
	recipients all over the world.[BR]
	His specialty is attacking[BR]
	airborne enemies.[End]
}

#message:28:(PartnerDesc_Parakarry_Pause_SkyDive1) {
	Kick an enemy.[End]
}

#message:28:(PartnerDesc_Parakarry_Pause_SkyDive2) {
	Kick an enemy.[End]
}

#message:28:(PartnerDesc_Parakarry_Pause_SkyDive3) {
	Kick an enemy.[End]
}

#message:28:(PartnerDesc_Parakarry_Pause_ShellShot) {
	Attack an enemy in the air[BR]
	by bumping into it.[End]
}

#message:28:(PartnerDesc_Parakarry_Pause_AirLift) {
	Carry an enemy away from[BR]
	the battle.[BR]
	Weaker enemies are more easily[BR]
	carried away.[End]
}

#message:28:(PartnerDesc_Parakarry_Pause_AirRaid) {
	Fly around like crazy, attacking[BR]
	all enemies.[End]
}

#message:28:(PartnerDesc_Bow_World) {
	Press [C-DOWN] to become transparent[BR]
	so objects will go through you.[End]
}

#message:28:(PartnerDesc_Bow_Battle) {
	She can become transparent,[BR]
	and her specialty is slapping.[End]
}

#message:28:(PartnerDesc_Bow_Battle_Smack) {
	Slap an enemy.[End]
}

#message:28:(PartnerDesc_Bow_Battle_OuttaSight) {
	Make Mario transparent so he[BR]
	can avoid enemy attacks.[End]
}

#message:28:(PartnerDesc_Bow_Battle_Spook) {
	Surprise enemies and scare[BR]
	them away from the fight.[End]
}

#message:28:(PartnerDesc_Bow_Battle_FanSmack) {
	Attack an enemy with a fan.[End]
}

#message:28:(PartnerDesc_Bow_Pause) {
	Bow is a princess of a Boo who[BR]
	has a castle in Forever Forest.[BR]
	Press [C-DOWN] to make the team[BR]
	invisible so it can elude attack.[BR]
	Her specialty is slapping the[BR]
	sense into enemies.[BR]
	[End]
}

#message:28:(PartnerDesc_Bow_Pause_Smack1) {
	Slap an enemy.[End]
}

#message:28:(PartnerDesc_Bow_Pause_Smack2) {
	Slap an enemy.[End]
}

#message:28:(PartnerDesc_Bow_Pause_Smack3) {
	Slap an enemy.[End]
}

#message:28:(PartnerDesc_Bow_Pause_OuttaSight) {
	Make Mario transparent so he[BR]
	can avoid enemy attacks.[End]
}

#message:28:(PartnerDesc_Bow_Pause_Spook) {
	Startle enemies and scare them[BR]
	away from battle.[End]
}

#message:28:(PartnerDesc_Bow_Pause_FanSmack) {
	Attack an enemy with a fan.[End]
}

#message:28:(PartnerDesc_Watt_World) {
	Press [C-DOWN] to illuminate the[BR]
	area and see invisible blocks.[End]
}

#message:28:(PartnerDesc_Watt_Battle) {
	Watt's great at penetrating[BR]
	defense and paralyzing enemies.[End]
}

#message:28:(PartnerDesc_Watt_Battle_ElectroDash) {
	Penetrate defense power and[BR]
	attack an enemy with electricity.[End]
}

#message:28:(PartnerDesc_Watt_Battle_PowerShock) {
	If it works, paralyze an enemy[BR]
	with an electric shock.[End]
}

#message:28:(PartnerDesc_Watt_Battle_TurboCharge) {
	Electrically boost Mario's attack[BR]
	power for a short time.[End]
}

#message:28:(PartnerDesc_Watt_Battle_MegaShock) {
	If it works, paralyze all enemies[BR]
	with an electric shock.[End]
}

#message:28:(PartnerDesc_Watt_Pause) {
	The child of Li'l Sparky, she[BR]
	can produce ample electricity.[BR]
	Press [C-DOWN] to illuminate areas[BR]
	and see invisible blocks.[BR]
	She's great at penetrating[BR]
	defenses and paralyzing enemies.[End]
}

#message:28:(PartnerDesc_Watt_Pause_ElectroDash1) {
	Penetrate defense power and[BR]
	attack an enemy with electricity.[End]
}

#message:28:(PartnerDesc_Watt_Pause_ElectroDash2) {
	Penetrate defense power and[BR]
	attack an enemy with electricity.[End]
}

#message:28:(PartnerDesc_Watt_Pause_ElectroDash3) {
	Penetrate defense power and[BR]
	attack an enemy with electricity.[BR]
	[End]
}

#message:28:(PartnerDesc_Watt_Pause_PowerShock) {
	If it works, paralyze an enemy[BR]
	with an electric shock.[End]
}

#message:28:(PartnerDesc_Watt_Pause_TurboCharge) {
	Electrically boost Mario's[BR]
	attack power for a short time.[End]
}

#message:28:(PartnerDesc_Watt_Pause_MegaShock) {
	If it works, paralyze all enemies[BR]
	with an electric shock.[End]
}

#message:28:(PartnerDesc_Sushie_World) {
	Press [C-DOWN] to ride Sushie, then[BR]
	press [C-DOWN] again to dive.[End]
}

#message:28:(PartnerDesc_Sushie_Battle) {
	Sushie is especially good at[BR]
	dousing enemies with water.[End]
}

#message:28:(PartnerDesc_Sushie_Battle_BellyFlop) {
	Flop on an enemy.[End]
}

#message:28:(PartnerDesc_Sushie_Battle_Squirt) {
	Squirt a powerful jet of water.[BR]
	Great for fire enemies.[End]
}

#message:28:(PartnerDesc_Sushie_Battle_WaterBlock) {
	Create a cube of water to boost[BR]
	Mario's defense briefly.[End]
}

#message:28:(PartnerDesc_Sushie_Battle_TidalWave) {
	Swim madly to create a wave[BR]
	that washes over all enemies.[End]
}

#message:28:(PartnerDesc_Sushie_Pause) {
	Sushie's a kindly Cheep Cheep[BR]
	who worries about everyone.[BR]
	She loves romantic stories and[BR]
	cries at the drop of a fin.[BR]
	Press [C-DOWN] once to ride the waves,[BR]
	again to dive below the surface.[BR]
	Sushie's specialty is the water[BR]
	attack.[BR]
	[End]
}

#message:28:(PartnerDesc_Sushie_Pause_BellyFlop1) {
	Flop on an enemy.[End]
}

#message:28:(PartnerDesc_Sushie_Pause_BellyFlop2) {
	Flop on an enemy.[End]
}

#message:28:(PartnerDesc_Sushie_Pause_BellyFlop3) {
	Flop on an enemy.[End]
}

#message:28:(PartnerDesc_Sushie_Pause_Squirt) {
	Squirt a powerful jet of water.[BR]
	Great for fire enemies.[End]
}

#message:28:(PartnerDesc_Sushie_Pause_WaterBlock) {
	Create a cube of water to boost[BR]
	Mario's defense briefly.[End]
}

#message:28:(PartnerDesc_Sushie_Pause_TidalWave) {
	Swim madly to create a wave[BR]
	that washes over all enemies.[End]
}

#message:28:(PartnerDesc_Lakilester_World) {
	Press [C-DOWN] to ride Lakilester[BR]
	and float over lava and spikes.[End]
}

#message:28:(PartnerDesc_Lakilester_Battle) {
	Throw a spiny egg at an enemy.[End]
}

#message:28:(PartnerDesc_Lakilester_Battle_SpinyFlip) {
	Throw a spiny egg at an enemy.[End]
}

#message:28:(PartnerDesc_Lakilester_Battle_SpinySurge) {
	Throw spiny eggs at all enemies.[End]
}

#message:28:(PartnerDesc_Lakilester_Battle_CloudNine) {
	Create a cloud to hide Mario[BR]
	for a short time.[End]
}

#message:28:(PartnerDesc_Lakilester_Battle_Hurricane) {
	If it works, blow the enemies[BR]
	away from the battle.[End]
}

#message:28:(PartnerDesc_Lakilester_Pause) {
	This wannabe talks like a tough[BR]
	guy to impress his girlfriend.[BR]
	Press [C-DOWN] to ride the cloud with[BR]
	him over spikes or lava.[BR]
	His specialty is throwing spiny[BR]
	eggs.[End]
}

#message:28:(PartnerDesc_Lakilester_Pause_SpinyFlip1) {
	Throw a spiny egg at an enemy.[End]
}

#message:28:(PartnerDesc_Lakilester_Pause_SpinyFlip2) {
	Throw a spiny egg at an enemy.[End]
}

#message:28:(PartnerDesc_Lakilester_Pause_SpinyFlip3) {
	Throw a spiny egg at an enemy.[End]
}

#message:28:(PartnerDesc_Lakilester_Pause_SpinySurge) {
	Throw spiny eggs at all enemies.[End]
}

#message:28:(PartnerDesc_Lakilester_Pause_CloudNine) {
	Create a cloud to hide Mario[BR]
	for a short time.[BR]
	While in the cloud, Mario will[BR]
	avoid enemy attacks.[End]
}

#message:28:(PartnerDesc_Lakilester_Pause_Hurricane) {
	If it works, blow the enemies[BR]
	away from the battle.[End]
}

#message:28:(PartnerDesc_Goombaria_World) {
	Press [C-DOWN] to have her tell you[BR]
	about everything nearby.[End]
}

#message:28:(PartnerDesc_Goombaria_Battle) {
	She can observe enemies.[BR]
	Her specialty is headbonking.[End]
}

#message:28:(PartnerDesc_Goombaria_Battle_Headbonk) {
	Headbonk an enemy.[End]
}

#message:28:(PartnerDesc_Goombaria_Battle_Tattle) {
	See enemy description and make[BR]
	HP visible.[End]
}

#message:28:(PartnerDesc_Goombaria_Battle_Charge) {
	Charge attack power. It goes up[BR]
	by 2 then returns to normal.[End]
}

#message:28:(PartnerDesc_Goombaria_Battle_Multibonk) {
	Headbonk continuously until[BR]
	you miss an action command.[End]
}

#message:28:(PartnerDesc_Goombaria_Pause) {
	Placeholder.[BR]
	[End]
}

#message:28:(PartnerDesc_Goombaria_Pause_Headbonk1) {
	Headbonk an enemy.[End]
}

#message:28:(PartnerDesc_Goombaria_Pause_Headbonk2) {
	Headbonk an enemy.[End]
}

#message:28:(PartnerDesc_Goombaria_Pause_Headbonk3) {
	Headbonk an enemy.[End]
}

#message:28:(PartnerDesc_Goombaria_Pause_Tattle) {
	See enemies' descriptions and[BR]
	see their HP during battle.[End]
}

#message:28:(PartnerDesc_Goombaria_Pause_Charge) {
	Charge to raise attack power[BR]
	by 2.[BR]
	You can charge unlimited times,[BR]
	but power fades after attack.[BR]
	[End]
}

#message:28:(PartnerDesc_Goombaria_Pause_Multibonk) {
	Headbonk continuously until[BR]
	you miss the action command.[End]
}
